#!/usr/bin/env bash
# ============================================================
# InvoiceMe - Local Development Startup Script
# Prerequisites: Docker, Supabase CLI (npx supabase)
# ============================================================
set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

echo ""
echo "=========================================="
echo "  InvoiceMe - Local Dev Setup"
echo "=========================================="
echo ""

# ---- 1. Check Docker is running ----
if ! docker info > /dev/null 2>&1; then
  echo "ERROR: Docker is not running. Please start Docker and try again."
  exit 1
fi

# ---- 2. Start Supabase local stack ----
echo "[1/3] Starting Supabase local stack..."
npx supabase start

echo ""
echo "[2/3] Supabase is running."
echo "      Studio: http://127.0.0.1:54323"
echo "      API:    http://127.0.0.1:54321"
echo ""

# ---- 3. Sync .env.local with actual local Supabase keys ----
SUPABASE_URL="http://127.0.0.1:54321"
ANON_KEY=$(npx supabase status --output json 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('anon_key',''))" 2>/dev/null || echo "")

if [ -n "$ANON_KEY" ]; then
  cat > .env.local <<EOF
# Supabase local dev (auto-generated by start.sh)
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
EOF
  echo "      .env.local updated with current Supabase keys."
else
  echo "      Using existing .env.local (could not auto-detect anon key)."
fi

echo ""
echo "[3/3] Starting Next.js dev server..."
echo ""
echo "  App:     http://localhost:3000"
echo "  Login:   dev@local.com / dev123456"
echo ""
echo "=========================================="
echo ""

npm run dev
